name: "[Build] Platform library"

on:
#   push:
#     branches:
#       - main
  workflow_dispatch: # Manual trigger from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean test package -Dplatform.version="0.0.${GITHUB_RUN_NUMBER}"
    #   - name: Upload Report
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: jacoco-report
    #       path: ${{ github.workspace }}/target/site/jacoco
    #   - name: Generate JaCoCo Badge
    #     uses: cicirello/jacoco-badge-generator@v2
    #     with:
    #       generate-coverage-badge: true
    #       generate-branches-badge: true
    #       coverage-badge-filename: jacoco.svg
    #       jacoco-csv-file: target/site/jacoco/jacoco.csv
    #   - name: Test Report
    #     uses: dorny/test-reporter@v1
    #     with:
    #       reporter: java-junit
    #       name: JUnit Tests
    #       list-tests: 'all'
    #       path: './**/TEST-*.xml'
    #       token: ${{ secrets.GH_DEPLOY_TOKEN }}
      - name: Publish package
        run: mvn --batch-mode deploy -Dplatform.version="0.0.${GITHUB_RUN_NUMBER}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
